In [1]:
import pandas as pd
df = pd.read_csv('supermarket.csv')
pt = df.pivot_table(index='Section', aggfunc='sum').reindex(['Revenue','Expense'], axis=1)
pt['Profit'] = pt['Revenue']-pt['Expense']
pt['Profit %'] = ((pt['Profit']/pt['Profit'].sum())*100).round(2)
pt.sort_values('Profit %', ascending=False)
pt['Cumulative %'] = pt['Profit %'].cumsum()
pt

                  Revenue  Expense   Profit  Profit %  Cumulative %
Section
Baked Goods       2487.04  1728.79   758.25      7.61          7.61
Baking            1259.16   716.38   542.78      5.45         13.06
Cheese            9917.75  6073.00  3844.75     38.58         51.64
Condiments        3264.66  1939.43  1325.23     13.30         64.94
Dairy             3267.02  2156.89  1110.13     11.14         76.08
Fresh Fruits      4463.33  4091.04   372.29      3.74         79.82
Fresh Vegetables  4162.04  2488.28  1673.76     16.79         96.61
Meat              5582.94  5243.99   338.95      3.40        100.01